name: Frontend Lint

on:
    pull_request:
        branches: [ main ]

jobs:
    lint:
        runs-on: ubuntu-latest
        defaults:
          run:
            working-directory: ./
        steps:
            - name: 📥 Checkout repo
              uses: actions/checkout@v4

            - name: 🟢 Use Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 18

            - name: 📦 Install dependencies
              run: npm ci
              
            - name: 🧪 Run ESlint
              run: npm run lint